name: ruby-test-notepad

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
      DATABASE_URL: postgresql://postgres:postgres@localhost/notepad_test

    services:
      db:
        image: postgres
        ports: ["5432:5432"]
        env:
          POSTGRES_DB: notepad_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0.1"

      - name: Run Install
        run: |
          sudo apt-get -yqq install libpq-dev
          gem update --system
          gem install rake -v 13.0.1
          gem install bundler -v "~>2.0"
          bundle install
      - name: Run Tests (rspec)
        run: |
          bundle exec rails db:create db:migrate
          bundle exec rspec